DROP TABLE IF EXISTS `kb_db_param`;
CREATE TABLE IF NOT EXISTS `kb_db_param` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MODEL` varchar(20),
  `NAME` varchar(50),
  `CODE` varchar(50),
  `VALUE` varchar(200),
  `DESC` varchar(200),
  `SORT_ID` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
insert into `kb_db_param` (`MODEL`,`NAME`,`CODE`,`VALUE`,`DESC`) values 
('SYS','系统名称','SYS_NAME','康佳技术服务平台',''),
('SYS','系统英文名称','SYS_EN_NAME','KonkaTSP',''),
('SYS','系统描述','SYS_DESC','精致产品 美妙生活',''),
('SYS','系统版本号','SYS_VERSION','v 2.0.0',''),
('SYS','应用路径','SYS_PATH','/KonkaTSP',''),
('SYS','应用网址','SYS_URL','127.0.0.1:8080','');

DROP TABLE IF EXISTS `kb_database`;
CREATE TABLE IF NOT EXISTS `kb_database` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PARENT_ID` int(11),
  `NAME` varchar(50),
  `CODE` varchar(50),
  `COLOR` varchar(20) NOT NULl DEFAULT 'none',
  `SORT_ID` int(11) NOT NULL DEFAULT 0,
  `ENABLE_FLAG` varchar(1) NOT NULL DEFAULT 'T',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

insert into kb_database (`PARENT_ID`,`NAME`,`CODE`,`COLOR`) values 
(0,'权限_打开方式','RIGHT_TARGET','none'),
(1,'面板','navTab','none'),
(1,'对话框','dialog','none'),
(0,'通用_是/否','TRUE/FALSE','none'),
(4,'是','true','none'),
(4,'否','false','none'),
(0,'权限_角色_所属模块','RIGHT_ROLE_MODEL','none'),
(7,'通用','COMMON','none'),
(7,'其它','OTHER','none'),
(0,'权限_部门_类别','RIGHT_DEPT_CATE','none'),
(10,'集团','JITUAN','none'),
(10,'公司','COMPANY','none'),
(10,'部门','DEPT','none'),
(10,'大组','B_GROUP','none'),
(10,'小组','S_GROUP','none'),
(10,'网点','NET','none'),
(10,'其它','OTHER','none'),
(0,'通用_可用/禁用','T/F','none'),
(18,'可用','T','none'),
(18,'禁用','F','none'),
(0,'权限_工作组_所属模块','RIGHT_GROUP_MODEL','none'),
(21,'通用','COMMON','none'),
(21,'其它','OTHER','none'),
(0,'基础数据_数据字典_颜色','DATABASE_COLOR','none'),
(24,'默认','none','none'),
(24,'红色','red','none'),
(24,'绿色','green','none'),
(24,'蓝色','blue','none'),
(24,'灰色','gray','none'),
(0,'基础数据_配置参数_所属模块','DATABASE_PARAM_MODEL','none'),
(30,'系统','SYS','none'),
(30,'其它','OTHER','none'),
(0,'通用_是/否','SHIFOU','none'),
(33,'是','T','none'),
(33,'否','F','none'),
(0,'在线考试_考题类型','EXAM_TOPIC_TYPE','none'), 
(36,'单选题','A','none'), 
(36,'多选题','B','none'), 
(36,'判断题','C','none'), 
(36,'填空题','D','none'), 
(36,'简答题','E','none'),
(0,'在线考试_人员考试状态','EXAM_USER_STATUS','none'),
(42,'尚未考试','WAITTING','none'),
(42,'考试中','EXAMING','none'),
(42,'已完成','SUBMIT','none'),
(0,'系统_分类模型','CONTENT_MODEL','none'),
(46,'文章','ARTICLE','none'),
(46,'下载','DOWNLOAD','none'),
(46,'视频','VIDEO','none'),
(46,'问答','ASK','none'),
(46,'考试','EXAM','none'),
(46,'论坛','BBS','none'),
(0,'在线考试_难道分级','EXAM_DIFF','none'),
(53,'0-未分级','0','none'),
(53,'1-非常容易','1','none'),
(53,'2-容易','2','none'),
(53,'3-一般','3','none'),
(53,'4-有难度','4','none'),
(53,'5-非常难','5','none'),
(0,'在线考试_试题排序','EXAM_TOPIC_SORT','none'),
(60,'人工排序','A','none'),
(60,'随机顺序','B','none'),
(60,'由易到难','C','none'),
(0,'在线考试_评分方法','EXAM_SCORE_TYPE','none'),
(64,'扣除总分','A','none'),
(64,'正确累加','B','none'),
(0,'问答_问题解答状态','ASK_SOLVE','none'),
(67,'待解决','F','red'),
(67,'已解决','T','green'),
(67,'已关闭','N','gray'),
(0,'公告_公告类别','NOTICE_CATEGORY','none'),
(71,'通知','A','none'),
(71,'活动','B','none'),
(71,'新闻','C','none'),
(71,'其它','Z','none'),
(0,'在线考试_成绩公布方式','EXAM_RESULT_TYPE','none'),
(76,'全体考完','A','none'),
(76,'个人考完','B','none'),
(0,'金币_变化方式','GOLD_CHANGE','none'),
(79,'增加','ADD','green'),
(79,'减少','CUT','red');