DROP TABLE IF EXISTS `kb_user_login`;
CREATE TABLE IF NOT EXISTS `kb_user_login` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `APP` VARCHAR(30),
  `IP` VARCHAR(50),
  `CLIENT` VARCHAR(30),
  `SESSIONID` VARCHAR(100),
  `DESTORY_TIME` TIMESTAMP,
	`CREATE_USER` varchar(50),
	`CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
