DROP TABLE IF EXISTS `kb_sys_uploadfile`;
CREATE TABLE IF NOT EXISTS `kb_sys_uploadfile` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MODEL` varchar(20),
  `FUN` varchar(30),
  `OBJECT_ID` INT(11),
  `IS_USE` VARCHAR(1) NOT NULL DEFAULT 'F',
  `FILENAME` VARCHAR(100),
  `FILEURL` VARCHAR(200),
  `FILESIZE` VARCHAR(30),
  `EXT` VARCHAR(30),
  `SEQ` VARCHAR(30),
	`CREATE_USER` varchar(50),
	`CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

ALTER TABLE `kb_sys_uploadfile`
MODIFY COLUMN `ID`  int(11) NULL AUTO_INCREMENT FIRST ,
ADD INDEX `MODEL` (`MODEL`) USING BTREE ,
ADD INDEX `FUN` (`FUN`) USING BTREE ,
ADD INDEX `OBJECT_ID` (`OBJECT_ID`) USING BTREE ,
ADD INDEX `IS_USE` (`IS_USE`) USING BTREE ,
ADD INDEX `CREATE_USER` (`CREATE_USER`) USING BTREE ,
ADD INDEX `CREATE_TIME` (`CREATE_TIME`) USING BTREE ;

