DROP TABLE "OPENEAP"."KB_DB_PARAM";
CREATE TABLE "OPENEAP"."KB_DB_PARAM"
 ("ID"              INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE, MINVALUE 1,NO MAXVALUE,NO CYCLE,ORDER), 
	"MODEL"           VARCHAR(20),
	"NAME"            VARCHAR(50),
	"CODE"            VARCHAR(50),
	"VALUE"           VARCHAR(200),
	"DESC"            VARCHAR(200),
	"SORT_ID"         INTEGER NOT NULL DEFAULT 0
 );
ALTER TABLE "OPENEAP"."KB_DB_PARAM" ADD CONSTRAINT "P_Key" PRIMARY KEY ("ID");
 
INSERT INTO "OPENEAP"."KB_DB_PARAM" ("MODEL","NAME","CODE","VALUE","DESC") VALUES 
('SYS','系统名称','SYS_NAME','KBOSS',''),
('SYS','应用路径','SYS_PATH','/KBOSS','');

DROP TABLE "OPENEAP"."KB_DATABASE";
CREATE TABLE "OPENEAP"."KB_DATABASE"
 ("ID"              INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE, MINVALUE 1,NO MAXVALUE,NO CYCLE,ORDER), 
	"PARENT_ID"       INTEGER,
	"NAME"            VARCHAR(50),
	"CODE"            VARCHAR(50),
	"COLOR"           VARCHAR(20) NOT NULL DEFAULT 'none',
	"SORT_ID"         INTEGER NOT NULL DEFAULT 0,
	"ENABLE_FLAG"     VARCHAR(1) NOT NULL DEFAULT 'T'
);
ALTER TABLE "OPENEAP"."KB_DATABASE" ADD CONSTRAINT "P_Key" PRIMARY KEY ("ID");	
//不在提供数据插入，请自行系统维护数据