DROP TABLE "OPENEAP"."KB_RIGHT_GROUP";
CREATE TABLE "OPENEAP"."KB_RIGHT_GROUP"
 ("ID"              INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE, MINVALUE 1,NO MAXVALUE,NO CYCLE,ORDER), 
 	"MODEL"           VARCHAR(20),
 	"NAME"            VARCHAR(100),
 	"DESC"            VARCHAR(200),
	"UPDATE_USER"     VARCHAR(50),
	"UPDATE_TIME"     TIMESTAMP,
	"CREATE_USER"     VARCHAR(50),
	"CREATE_TIME"     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
 ); 
 
INSERT INTO "OPENEAP"."KB_RIGHT_GROUP" ("MODEL","NAME","DESC") VALUES ('COMMON','通用工作组','默认');

DROP TABLE "OPENEAP"."KB_RIGHT_GROUP_USER";
CREATE TABLE "OPENEAP"."KB_RIGHT_GROUP_USER"
 ("USERNAME"              VARCHAR(50), 
  "GROUP_ID"               INTEGER
 ); 
 
INSERT INTO "OPENEAP"."KB_RIGHT_GROUP_USER" ("USERNAME","GROUP_ID") VALUES ('admin',1);