DROP TABLE "OPENEAP"."KB_RIGHT_ROLE";
CREATE TABLE "OPENEAP"."KB_RIGHT_ROLE"
 ("ID"              INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE, MINVALUE 1,NO MAXVALUE,NO CYCLE,ORDER), 
	"MODEL"           VARCHAR(20),
	"NAME"            VARCHAR(100),
	"DESC"            VARCHAR(200),
	"UPDATE_USER"     VARCHAR(50),
	"UPDATE_TIME"     TIMESTAMP,
	"CREATE_USER"     VARCHAR(50),
	"CREATE_TIME"     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE "OPENEAP"."KB_RIGHT_ROLE" ADD CONSTRAINT "P_Key" PRIMARY KEY ("ID");

INSERT INTO "OPENEAP"."KB_RIGHT_ROLE" ("MODEL","NAME","DESC") VALUES ('COMMON','超级管理员','拥有系统所有功能的权限');

DROP TABLE "OPENEAP"."KB_RIGHT_ROLE_RIGHT";
CREATE TABLE "OPENEAP"."KB_RIGHT_ROLE_RIGHT"
 ("ROLE_ID"              INTEGER, 
  "RIGHT_ID"              INTEGER
 ); 

INSERT INTO "OPENEAP"."KB_RIGHT_ROLE_RIGHT" ("ROLE_ID" ,"RIGHT_ID" ) VALUES 
(1,1),
(1,2),
(1,3),
(1,4),
(1,5),
(1,6),
(1,7),
(1,8),
(1,9),
(1,10);

DROP TABLE "OPENEAP"."KB_RIGHT_USER_ROLE";
CREATE TABLE "OPENEAP"."KB_RIGHT_USER_ROLE"
 ("USERNAME"              VARCHAR(50), 
  "ROLE_ID"               INTEGER
 ); 

INSERT INTO "OPENEAP"."KB_RIGHT_USER_ROLE" ("USERNAME","ROLE_ID") VALUES ('admin',1);