DROP TABLE "OPENEAP"."KB_SYS_UPLOADFILE";
CREATE TABLE "OPENEAP"."KB_SYS_UPLOADFILE"
 ("ID"              INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE, MINVALUE 1,NO MAXVALUE,NO CYCLE,ORDER), 
  "MODEL"           VARCHAR(20),
  "FUN"             VARCHAR(30),
  "OBJECT_ID"       INTEGER,
  "IS_USE"          VARCHAR(1) NOT NULL DEFAULT 'F',
  "FILENAME"        VARCHAR(100),
  "FILEURL"         VARCHAR(200),
  "FILESIZE"        VARCHAR(30),
  "EXT"             VARCHAR(30),
  "SEQ"             VARCHAR(30),
	"CREATE_USER"     VARCHAR(50),
	"CREATE_TIME"     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);