DROP TABLE "OPENEAP"."KB_USER_LOGIN";
CREATE TABLE "OPENEAP"."KB_USER_LOGIN"
 ("ID"              INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE, MINVALUE 1,NO MAXVALUE,NO CYCLE,ORDER), 
  "APP"             VARCHAR(30),
  "IP"              VARCHAR(50),
  "CLIENT"          VARCHAR(30),
  "SESSIONID"       VARCHAR(100),
  "DESTORY_TIME"    TIMESTAMP,
	"CREATE_USER"     VARCHAR(50),
	"CREATE_TIME"     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);